#!/usr/bin/python

import os
import re

rp = re.compile("(cu)$")

for root, dirs, files in os.walk("."):
    if root.endswith("/Make"):
        newlines = []
        with open(root+'/files','r') as f:
            for line in f.readlines():
                newlines.append(rp.sub('C', line))
        if newlines:
            with open(root+'/files', 'w') as f:
                for line in newlines:
                    f.write(line)

