

using Foam::label;
using Foam::scalar;
using Foam::vector;
using Foam::tensor;
using Foam::symmTensor;
using Foam::Switch;
using Foam::word;

using Foam::I;

using Foam::GREAT;
using Foam::VGREAT;
using Foam::ROOTVGREAT;
using Foam::SMALL;
using Foam::VSMALL;
using Foam::ROOTVSMALL;

using Foam::Time;
using Foam::argList;
using Foam::Info;
using Foam::IOobject;
using Foam::IOdictionary;
using Foam::dictionary;
using Foam::endl;
using Foam::nl;

using Foam::autoPtr;
using Foam::tmp;
using Foam::pTraits;

//- dimensionSet options
using Foam::dimensionSet;
using Foam::dimless;

using Foam::dimMass;
using Foam::dimLength;
using Foam::dimTime;
using Foam::dimTemperature;
using Foam::dimMoles;
using Foam::dimCurrent;
using Foam::dimLuminousIntensity;

using Foam::dimArea;
using Foam::dimVolume;
using Foam::dimVol;

using Foam::dimDensity;
using Foam::dimForce;
using Foam::dimEnergy;
using Foam::dimPower;

using Foam::dimVelocity;
using Foam::dimAcceleration;
using Foam::dimPressure;
using Foam::dimGasConstant;
using Foam::dimSpecificHeatCapacity;
using Foam::dimViscosity;

using Foam::dimensionedScalar;
using Foam::dimensionedVector;
using Foam::dimensionedTensor;
using Foam::dimensionedSymmTensor;

using Foam::List;
using Foam::wordList;
using Foam::PtrList;
using Foam::labelList;

//- Field options
using Foam::scalargpuField;
using Foam::labelgpuList;
using Foam::GeometricField;

using Foam::FatalError;
using Foam::FatalIOError;

namespace constant = Foam::constant;


