#!/usr/bin/python

import os
import re

p = re.compile("(.+)\.C$")

for root, dirs, files in os.walk("."):
    for name in files:
        m = p.match(name)
        if m is not None:
            try:
                os.symlink(name,root+"/"+m.group(1)+".cu");
            except OSError:
                pass

