/*---------------------------------------------------------------------------*\
  =========                 |
  \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
   \\    /   O peration     |
    \\  /    A nd           | Copyright (C) 2011 OpenFOAM Foundation
     \\/     M anipulation  |
-------------------------------------------------------------------------------
License
    This file is part of OpenFOAM.

    OpenFOAM is free software: you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
    FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
    for more details.

    You should have received a copy of the GNU General Public License
    along with OpenFOAM.  If not, see <http://www.gnu.org/licenses/>.

\*---------------------------------------------------------------------------*/

#undef UNARY_FUNCTION

#undef UNARY_OPERATOR

#undef BINARY_FUNCTION

#undef BINARY_TYPE_FUNCTION_SF
#undef BINARY_TYPE_FUNCTION_FS
#undef BINARY_TYPE_FUNCTION

#undef BINARY_FULL_FUNCTION
#undef BINARY_SYM_FUNCTION

#undef BINARY_OPERATOR
#undef BINARY_OPERATOR_FUNC

#undef BINARY_TYPE_OPERATOR_SF
#undef BINARY_TYPE_OPERATOR_FS
#undef BINARY_TYPE_OPERATOR

#undef BINARY_FULL_OPERATOR
#undef BINARY_SYM_OPERATOR

#undef NO_SQR
#undef PSTREAM_DEFAULT

#undef PRODUCT_OPERATOR

#undef TEMPLATE
#undef VS_TEMPLATE

#undef FTYPE
#undef TYPE_1
#undef TYPE_2
#undef VS_TYPE
#undef FORM_TYPE

// ************************************************************************* //
